---
substitutions:
  open_switch: ch_1_switch
  open_current_sensor: ch_1_current
  close_switch: ch_2_switch
  close_current_sensor: ch_2_current
  start_sensing_delay: 1s

packages:
  device: !include ./shelly/shelly-plus-2pm-base.yaml
  use_case: !include ../common/cover.yaml
