---
substitutions:
  temperature_sensor_id: temperature
  heater_switch_id: ch_1_switch
  one_wire_pin: GPIO0

packages:
  device: !include ./shelly/shelly-plus-2pm-base.yaml
  floor_temperature: !include ./sensors/temperature-ds18b20.yaml
  use_case: !include ../common/thermostat.yaml
