substitutions:
  project_name: Thermostat
  project_version: "0.0.3"
  temperature_sensor_id: temperature
  heater_switch_id: ch_1_switch
  one_wire_pin: GPIO0

packages:
  base: !include ../common/base.yaml
  device_base: !include ./shelly/shelly-plus-2pm-base.yaml
  floor_temperature: !include ./sensors/temperature-ds18b20.yaml
  thermostat: !include ../common/thermostat.yaml
