substitutions:
  project_name: Tilt Cover
  project_version: "0.0.1"
  open_switch: ch_1_switch
  open_current_sensor: ch_1_current
  close_switch: ch_2_switch
  close_current_sensor: ch_2_current
  max_duration: 30s
  start_sensing_delay: 500ms

packages:
  base: !include ../common/base.yaml
  device_base: !include ./shelly/shelly-plus-2pm-base.yaml
  cover: !include ../common/cover.yaml
