---
substitutions:
  relay_count: 3

  light_1_id: light_1
  light_1_name: ${friendly_name} L1
  light_1_virtual: "false"

  light_2_id: light_2
  light_2_name: ${friendly_name} L2
  light_2_virtual: "false"

  light_3_id: light_3
  light_3_name: ${friendly_name} L3
  light_3_virtual: "false"

packages:
  device: !include ./sonoff/tx-ultimate/sonoff-tx-ultimate-base.yaml
  btn_action: !include ./sonoff/tx-ultimate/handle-release-3ch.yaml
  light_1: !include
    file: ../common/light.yaml
    vars:
      light_name: ${light_1_name}
      light_id: ${light_1_id}
      relay_id: relay_1
      is_virtual: ${light_1_virtual}
  light_2: !include
    file: ../common/light.yaml
    vars:
      light_name: ${light_2_name}
      light_id: ${light_2_id}
      relay_id: relay_2
      is_virtual: ${light_2_virtual}
  light_3: !include
    file: ../common/light.yaml
    vars:
      light_name: ${light_3_name}
      light_id: ${light_3_id}
      relay_id: relay_3
      is_virtual: ${light_3_virtual}
