---
script:
  - id: handle_release
    mode: restart
    parameters:
      pos: int
    then:
      - if:
          condition:
            lambda: "return pos <= 5;"
          then:
            - light.toggle: ${light_1_id}
          else:
            - light.toggle: ${light_2_id}
