---
script:
  - id: handle_release
    mode: restart
    parameters:
      pos: int
    then:
      - if:
          condition:
            lambda: "return pos <= 3;"
          then:
            - light.toggle: ${light_1_id}
          else:
            - if:
                condition:
                  lambda: "return pos <= 7;"
                then:
                  - light.toggle: ${light_2_id}
                else:
                  - light.toggle: ${light_3_id}
