---
substitutions:
  base_version: 1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  project:
    name: Orion.${project_name}
    version: ${base_version}.${project_version}-${device_version}

api:

logger:
  initial_level: INFO

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name}
    password: !secret wifi_ap_password

captive_portal:

select:
  - platform: logger
    name: ${friendly_name} Log Level

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
    mac_address:
      name: ${friendly_name} MAC Address
  - platform: version
    name: ${friendly_name} ESPHome Version
    hide_timestamp: true

button:
  - platform: restart
    name: ${friendly_name} Restart
  - platform: safe_mode
    name: ${friendly_name} Restart (Safe Mode)
