esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  project:
    name: Orion.${project_name}
    version: ${project_version}

api:

logger:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name}
    password: !secret wifi_ap_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
    mac_address:
      name: ${friendly_name} MAC Address
