---
substitutions:
  project_name: Thermostat
  project_version: "4"

climate:
  - platform: thermostat
    id: my_thermostat
    name: ${thermostat_name}
    sensor: ${temperature_sensor_id}
    min_heating_off_time: 60s
    min_heating_run_time: 30s
    min_idle_time: 30s
    visual:
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
    heat_deadband: 0 째C
    heat_action:
      - switch.turn_on: ${heater_switch_id}
    idle_action:
      - switch.turn_off: ${heater_switch_id}
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 23 째C
      - name: Away
        default_target_temperature_low: 16 째C
      - name: On (Manual)
        default_target_temperature_low: 30 째C
