wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: $friendly_name
    password: !secret wifi_ap_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
