substitutions:
  one_wire_pin: GPIO0
  temperature_sensor_id: temperature
  temperature_sensor_name: Temperature
  temperature_offset: "0"

one_wire:
  - platform: gpio
    pin: ${one_wire_pin}

sensor:
  - platform: dallas_temp
    address: ${ds18b20_address}
    name: ${temperature_sensor_name}
    id: ${temperature_sensor_id}
    update_interval: 60s
    filters:
      - offset: ${temperature_offset}
