---
binary_sensor:
  - platform: template
    name: ${touchfield_name}
    id: ${touchfield_id}
    on_press:
      - switch.toggle: ${relay_id}
      - delay: ${button_on_time}
      - binary_sensor.template.publish:
          id: ${touchfield_name}
          state: OFF
      - script.execute: refresh_led_default

switch:
  - platform: gpio
    id: ${relay_id}
    name: ${relay_name}
    pin: ${relay_pin}
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - script.execute: refresh_led_default
    on_turn_off:
      then:
        - script.execute: refresh_led_default
