substitutions:
  name: "shelly-plus-2pm-2"
  friendly_name: Shelly Plus 2PM 2
  thermostat_name: Konyha termosztát
  temperature_sensor_name: Konyha hőmérséklet
  temperature_offset: "-10"
  ds18b20_address: "0xd205032934646128"

packages:
  base: !include ./devices/shelly-plus-2pm-thermostat.yaml
