substitutions:
  name: "shelly-plus-2pm-4"
  friendly_name: Shelly Plus 2PM 4
  thermostat_name: Háló termosztát
  temperature_sensor_name: Háló hőmérséklet
  temperature_offset: "-10"
  ds18b20_address: "0xd205032934646128"

packages:
  base: !include ./devices/shelly-plus-2pm-thermostat.yaml
