---
substitutions:
  name: "shelly-plus-2pm-6"
  friendly_name: Shelly Plus 2PM 6
  thermostat_name: Zuhanyzó termosztát
  temperature_sensor_name: Zuhanyzó hőmérséklet
  temperature_offset: "-0.1"
  ds18b20_address: "0x1568fe2b34646128"

packages:
  base: !include ./devices/shelly-plus-2pm-thermostat.yaml
