substitutions:
  name: "shelly-plus-2pm-24"
  friendly_name: Shelly Plus 2PM 24
  project_name: Sandbox
  project_version: "0.0.1"

packages:
  base: !include ./common/base.yaml
  device-base: !include ./devices/shelly/shelly-plus-2pm-base.yaml
