substitutions:
  name: "shelly-plus-2pm-23"
  friendly_name: Shelly Plus 2PM 23
  cover_name: Boti szoba északi zsaluzia
  open_current_threshold: "0.45"
  open_obstacle_current_threshold: "0.8"
  open_duration: 45s
  close_current_threshold: "0.45"
  close_obstacle_current_threshold: "0.8"
  close_duration: 45s
  max_duration: 60s

packages:
  base: !include ./devices/shelly-plus-2pm-tilt-cover.yaml
