substitutions:
  name: "shelly-plus-2pm-7"
  friendly_name: Shelly Plus 2PM 7
  thermostat_name: Hálószoba termosztát
  temperature_sensor_name: Hálószoba hőmérséklet
  temperature_offset: "-1.1"
  ds18b20_address: "0x0375142834646128"

packages:
  base: !include ./devices/shelly-plus-2pm-thermostat.yaml
