substitutions:
  name: "shelly-plus-2pm-5"
  friendly_name: Shelly Plus 2PM 5
  thermostat_name: Zuhanyzó termosztát
  temperature_sensor_name: Zuhanyzó hőmérséklet
  temperature_offset: "-10"
  ds18b20_address: "0xd205032934646128"

packages:
  base: !include ./devices/shelly-plus-2pm-thermostat.yaml
