---
substitutions:
  name: "shelly-plus-2pm-13"
  friendly_name: Shelly Plus 2PM 13
  cover_name: Konyha ablak zsaluzia
  open_current_threshold: "0.45"
  open_obstacle_current_threshold: "0.8"
  open_duration: 18s
  close_current_threshold: "0.45"
  close_obstacle_current_threshold: "0.8"
  close_duration: 18s
  max_duration: 23s

packages:
  base: !include ./devices/shelly-plus-2pm-tilt-cover.yaml
