substitutions:
  name: "shelly-plus-2pm-19"
  friendly_name: Shelly Plus 2PM 19
  cover_name: Terasz ajtó zsaluzia
  open_current_threshold: "0.45"
  open_obstacle_current_threshold: "0.8"
  open_duration: 66s
  close_current_threshold: "0.45"
  close_obstacle_current_threshold: "0.8"
  close_duration: 68s
  max_duration: 73s

packages:
  base: !include ./devices/shelly-plus-2pm-tilt-cover.yaml
