substitutions:
  name: "shelly-plus-2pm-1"
  friendly_name: Shelly Plus 2PM 1
  thermostat_name: Nappali termosztát
  temperature_sensor_name: Nappali hőmérséklet
  temperature_offset: "-10"
  ds18b20_address: "0xd205032934646128"

packages:
  base: !include ./devices/shelly-plus-2pm-thermostat.yaml
