substitutions:
  name: "shelly-plus-2pm-6"
  friendly_name: Shelly Plus 2PM 6
  thermostat_name: Gyerekszoba 1 termosztát
  temperature_sensor_name: Gyerekszoba 1 hőmérséklet
  temperature_offset: "-10"
  ds18b20_address: "0xd205032934646128"

packages:
  base: !include ./devices/shelly-plus-2pm-thermostat.yaml
